name: Generar EXE Portable

on: [push]

jobs:
  build:
    runs-on: windows-2022 # Forzamos una versión estable de Windows
    steps:
    - uses: actions/checkout@v4

    - name: Instalar Dependencias
      run: |
        vcpkg install sdl2:x64-windows
        vcpkg install vigemclient:x64-windows

    - name: Compilar Proyecto
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build --config Release

    - name: Entregar el EXE
      uses: actions/upload-artifact@v4
      with:
        name: Emulador-Portable
        path: build/Release/XInputEmu.exe
